DROP TABLE IF EXISTS USER;

CREATE TABLE USER (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(200)
);
INSERT INTO USER VALUES (1, 'JOE SCAMANDER');
INSERT INTO USER VALUES (2, 'SILLY FILLY');
INSERT INTO USER VALUES (3, 'MOLLY EVANS');